// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForCreateLogs implements pgx.CopyFromSource.
type iteratorForCreateLogs struct {
	rows                 []CreateLogsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLogs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLogs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ServiceName,
		r.rows[0].LogLevel,
		r.rows[0].Message,
		r.rows[0].CreatedAt,
		r.rows[0].TraceID,
		r.rows[0].Metadata,
	}, nil
}

func (r iteratorForCreateLogs) Err() error {
	return nil
}

func (q *Queries) CreateLogs(ctx context.Context, arg []CreateLogsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"logs"}, []string{"service_name", "log_level", "message", "created_at", "trace_id", "metadata"}, &iteratorForCreateLogs{rows: arg})
}
