// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID          int64
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
	IngestedAt  pgtype.Timestamptz
}
