// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID          int64
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
	IngestedAt  pgtype.Timestamptz
	TraceID     pgtype.Text
	Metadata    []byte
}

type LogsY2026m05W1 struct {
	ID          int64
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
	IngestedAt  pgtype.Timestamptz
	TraceID     pgtype.Text
	Metadata    []byte
}

type LogsY2026m05W2 struct {
	ID          int64
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
	IngestedAt  pgtype.Timestamptz
	TraceID     pgtype.Text
	Metadata    []byte
}

type LogsY2026m05W3 struct {
	ID          int64
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
	IngestedAt  pgtype.Timestamptz
	TraceID     pgtype.Text
	Metadata    []byte
}

type LogsY2026m05W4 struct {
	ID          int64
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
	IngestedAt  pgtype.Timestamptz
	TraceID     pgtype.Text
	Metadata    []byte
}

type LogsY2026m05W5 struct {
	ID          int64
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
	IngestedAt  pgtype.Timestamptz
	TraceID     pgtype.Text
	Metadata    []byte
}
