// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (service_name, log_level, message)
VALUES ($1, $2, $3)
RETURNING id, service_name, log_level, message, created_at
`

type CreateLogParams struct {
	ServiceName string
	LogLevel    string
	Message     string
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, createLog, arg.ServiceName, arg.LogLevel, arg.Message)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.LogLevel,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
