// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (service_name, log_level, message, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, service_name, log_level, message, created_at, ingested_at
`

type CreateLogParams struct {
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, createLog,
		arg.ServiceName,
		arg.LogLevel,
		arg.Message,
		arg.CreatedAt,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.LogLevel,
		&i.Message,
		&i.CreatedAt,
		&i.IngestedAt,
	)
	return i, err
}

type CreateLogsParams struct {
	ServiceName string
	LogLevel    string
	Message     string
	CreatedAt   pgtype.Timestamptz
}
